name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ros_distro: humble
            experimental: false
          - ros_distro: jazzy
            experimental: false
          - ros_distro: lyrical      
            experimental: true
    container: ros:${{ matrix.ros_distro }}
    steps:
      - uses: actions/checkout@v4

      - name: Resolve dependencies
        run: |
          apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -y

      - name: Install Python dependencies
        run: |
          pip3 install web3 eth-account cryptography python-dotenv

      - name: Build
        shell: bash
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          colcon build

      - name: Test
        shell: bash
        run: |
          source /opt/ros/${{ matrix.ros_distro }}/setup.bash
          colcon test --event-handlers console_direct+ --return-code-on-test-failure
          colcon test-result --verbose --all


